version: '3.7'
services:
    nginx:
        image: nginx:alpine
        container_name: reports-nginx
        restart: on-failure
        volumes:
            - '.:/usr/src/reports:cached'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - "8080:88"
        depends_on:
            - php
        networks:
            - panel-network
    php:
        container_name: reports-php
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        restart: on-failure
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1 remote_autostart=1
            XDEBUG_KEY: pub
            PHP_IDE_CONFIG: serverName=DOCKER
            TIMEZONE: Europe/Madrid
        volumes:
            - .:/usr/src/reports:cached
            - ~/.ssh:/root/.ssh:ro
            - ~/.composer:/root/.composer
        networks:
            - panel-network
    db:
        image: mysql:latest
        container_name: reports-db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: vidoomy-adv
            MYSQL_ROOT_PASSWORD: 123123123
            MYSQL_USER: vidoomy
            MYSQL_PASSWORD: 123123123
        ports:
            - "3308:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        networks:
            panel-network:
                ipv4_address: 172.25.0.16
networks:
    panel-network:
        external: true
        name: panel-network
